# variables accesible by {{ site.variableName }}
title: Three Rax Bot
email: ealatuhin+starcraftbot@gmail.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog
url: "aardvark.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: muhango
github_username: aardvark

# Build settings
markdown: kramdown
theme: jekyll-theme-minimal
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true
